### ISSUE TITLE
[11.0] The container is behind the navbar

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_website#1]
![image](https://user-images.githubusercontent.com/5981417/34471436-e7ce4e60-ef49-11e7-98a5-ea51af086efd.png)

It would be great if you added a feature for logo resizing.

**Comment by keshrath** [comment]
Hello, that is kinda the wanted behavior :) If you only want to have the transparent navbar on your homepage you just have to change a few things, but I would recommend you to just put an upper banner on every page, but any widget with a background image should do the trick.

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/34471819-b27ab7a4-ef52-11e7-890b-510e6234cc14.png)

**Comment by keshrath** [comment]
Odoo, for example uses the same trick.

**Comment by keshrath** [comment]
What do you mean by logo resize?

**Comment by satriani-vai** [comment]
I mean, the ability to resize the logo. Because in Odoo 11 it is very tricky.

**Comment by keshrath** [comment]
I will look into it :)
