### ISSUE TITLE
Remaining modules upgrade to v12

### ISSUE THREAD

**Issue by spacimek** [muk-it/muk_website#4]
Hi guys, is there any plan to upgrade muk_website_navbar_transparent and muk_website_customize_gradient to v12? Do you need any help with that?

**Comment by keshrath** [comment]
At the moment our focus is not on the website modules. Some have already been migrated to version 12, but the rest is not planned yet. You are welcome to migrate one of the modules and make a pull request.

**Comment by spacimek** [comment]
Sure, thanks for letting me know. We might have some project in couple of weeks that can use those, so in that case we'll work on those and let you know.
