### ISSUE TITLE
Can't add content other then "Internal"

### ISSUE THREAD

**Issue by killday** [muk-it/muk_website#6]
Hi very good module,

I'm using Odoo version 12 and can't add other content in to the grid except from group Internal.
Also can't add image when columns set other than small grid.

Is there some basic using documentation?

Thanks

**Comment by keshrath** [comment]
You have an Option to switch to **Activate Structure** instead of **Activate Content**

**Comment by killday** [comment]
What this two options mean and do?

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/78998830-b48a1a00-7b49-11ea-8138-e10d08d3d84a.png)

**Comment by keshrath** [comment]
Activate the **Structure** option, to be able to add other content as well.
